
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'E657A5887A35FBF4D2C56DFCA1C756D3'
    
_lr_action_items = {'RPARAMC':([32,33,34,38,39,40,41,45,62,64,66,67,68,69,70,72,74,],[-27,-26,49,-25,-19,57,-10,59,-18,-24,-21,-22,-17,-23,-28,-9,-20,]),'IGUAL':([16,32,33,36,38,55,64,69,70,],[25,-27,-26,53,-25,53,-24,-23,-28,]),'OP_NOT':([22,26,37,48,50,],[35,35,35,35,35,]),'LJOIN':([0,21,25,27,47,71,],[4,4,4,4,4,4,]),'SELECT':([0,21,25,27,47,71,],[5,5,5,5,5,5,]),'FJOIN':([0,21,25,27,47,71,],[6,6,6,6,6,6,]),'TJOIN':([0,21,25,27,47,71,],[7,7,7,7,7,7,]),'RJOIN':([0,21,25,27,47,71,],[8,8,8,8,8,8,]),'RPARAM':([28,30,31,32,33,38,39,46,54,55,60,61,62,63,64,66,67,68,69,70,73,74,75,76,77,],[-13,-12,-11,-27,-26,-25,-19,60,68,69,-7,73,-18,74,-24,-21,-22,-17,-23,-28,-29,-20,69,77,-8,]),'EXCEPT':([0,21,25,27,47,71,],[10,10,10,10,10,10,]),'PUNTO':([38,],[56,]),'OP_LOGICO':([32,33,34,38,39,45,54,62,63,64,66,67,68,69,70,74,],[-27,-26,48,-25,-19,48,48,-18,48,-24,-21,-22,-17,-23,-28,-20,]),'NUM':([22,26,37,48,50,51,52,53,65,],[33,33,33,33,33,33,33,33,33,]),'OP_COMPARACION':([32,33,36,38,55,64,69,70,],[-27,-26,52,-25,52,-24,-23,-28,]),'$end':([3,11,18,19,41,42,43,44,60,72,73,77,],[-2,-1,-3,0,-10,-5,-4,-6,-7,-9,-29,-8,]),'STRING':([22,26,37,48,50,51,52,53,65,],[32,32,32,32,32,32,32,32,32,]),'NJOIN':([0,21,25,27,47,71,],[12,12,12,12,12,12,]),'UNION':([0,21,25,27,47,71,],[13,13,13,13,13,13,]),'PROJECT':([0,21,25,27,47,71,],[14,14,14,14,14,14,]),'PARENC':([4,5,6,7,8,14,17,],[-34,22,-36,-33,-35,24,26,]),'INTERSECT':([0,21,25,27,47,71,],[15,15,15,15,15,15,]),'COMA':([28,29,30,31,41,60,73,77,],[-13,47,-12,-11,58,-7,-29,-8,]),'PAREN':([1,2,5,9,10,12,13,15,20,22,23,26,35,37,48,49,50,51,52,53,57,59,65,],[21,-31,-16,-30,-40,-37,-38,-39,27,37,-14,37,50,37,37,-15,37,65,65,65,71,-32,65,]),'ID':([0,21,22,24,25,26,27,37,47,48,50,51,52,53,56,58,65,71,],[16,31,38,41,41,38,31,38,31,38,38,38,38,38,70,41,38,31,]),'OP_ARITMETICO':([32,33,36,38,55,64,66,67,69,70,75,],[-27,-26,51,-25,51,-24,51,51,-23,-28,51,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'op_join_arg':([0,21,25,27,47,71,],[9,9,9,9,9,9,]),'op_binario':([0,21,25,27,47,71,],[1,1,1,1,1,1,]),'op_select_opc':([5,],[23,]),'join_func':([0,21,25,27,47,71,],[17,17,17,17,17,17,]),'binario':([0,21,25,27,47,71,],[2,2,2,2,2,2,]),'asign':([0,],[18,]),'campos':([24,25,58,],[40,44,72,]),'condicion':([22,26,37,48,50,],[34,45,54,62,63,]),'biexp':([0,21,25,27,47,71,],[3,28,42,28,28,28,]),'exp':([0,],[19,]),'arg':([21,27,47,71,],[29,46,61,76,]),'cond_exp':([22,26,37,48,50,51,52,53,65,],[36,36,55,36,36,64,66,67,75,]),'op_select':([0,21,25,27,47,71,],[20,20,20,20,20,20,]),'unexp':([0,21,25,27,47,71,],[11,30,43,30,30,30,]),'op_condicion':([22,26,37,48,50,],[39,39,39,39,39,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp","S'",1,None,None,None),
  ('exp -> unexp','exp',1,'p_e1','ra2sql.py',61),
  ('exp -> biexp','exp',1,'p_e1','ra2sql.py',62),
  ('exp -> asign','exp',1,'p_e2','ra2sql.py',69),
  ('asign -> ID IGUAL unexp','asign',3,'p_a1','ra2sql.py',76),
  ('asign -> ID IGUAL biexp','asign',3,'p_a1','ra2sql.py',77),
  ('asign -> ID IGUAL campos','asign',3,'p_a2','ra2sql.py',89),
  ('unexp -> op_select PAREN arg RPARAM','unexp',4,'p_u1','ra2sql.py',107),
  ('unexp -> PROJECT PARENC campos RPARAMC PAREN arg RPARAM','unexp',7,'p_u2','ra2sql.py',127),
  ('campos -> ID COMA campos','campos',3,'p_c1','ra2sql.py',155),
  ('campos -> ID','campos',1,'p_c2','ra2sql.py',161),
  ('arg -> ID','arg',1,'p_ar1','ra2sql.py',166),
  ('arg -> unexp','arg',1,'p_ar2','ra2sql.py',170),
  ('arg -> biexp','arg',1,'p_ar2','ra2sql.py',171),
  ('op_select -> SELECT op_select_opc','op_select',2,'p_sl','ra2sql.py',176),
  ('op_select_opc -> PARENC condicion RPARAMC','op_select_opc',3,'p_sl_opc','ra2sql.py',181),
  ('op_select_opc -> <empty>','op_select_opc',0,'p_sl_opc','ra2sql.py',182),
  ('condicion -> PAREN condicion RPARAM','condicion',3,'p_cond1','ra2sql.py',191),
  ('condicion -> condicion OP_LOGICO condicion','condicion',3,'p_cond2','ra2sql.py',197),
  ('condicion -> op_condicion','condicion',1,'p_cond3','ra2sql.py',202),
  ('condicion -> OP_NOT PAREN condicion RPARAM','condicion',4,'p_cond4','ra2sql.py',207),
  ('op_condicion -> cond_exp OP_COMPARACION cond_exp','op_condicion',3,'p_oc','ra2sql.py',212),
  ('op_condicion -> cond_exp IGUAL cond_exp','op_condicion',3,'p_oc','ra2sql.py',213),
  ('cond_exp -> PAREN cond_exp RPARAM','cond_exp',3,'p_ce1','ra2sql.py',221),
  ('cond_exp -> cond_exp OP_ARITMETICO cond_exp','cond_exp',3,'p_ce2','ra2sql.py',226),
  ('cond_exp -> ID','cond_exp',1,'p_ce3','ra2sql.py',235),
  ('cond_exp -> NUM','cond_exp',1,'p_ce3','ra2sql.py',236),
  ('cond_exp -> STRING','cond_exp',1,'p_ce3','ra2sql.py',237),
  ('cond_exp -> ID PUNTO ID','cond_exp',3,'p_ce4','ra2sql.py',242),
  ('biexp -> op_binario PAREN arg COMA arg RPARAM','biexp',6,'p_b','ra2sql.py',247),
  ('op_binario -> op_join_arg','op_binario',1,'p_ob','ra2sql.py',302),
  ('op_binario -> binario','op_binario',1,'p_ob','ra2sql.py',303),
  ('op_join_arg -> join_func PARENC condicion RPARAMC','op_join_arg',4,'p_ob_arg','ra2sql.py',309),
  ('join_func -> TJOIN','join_func',1,'p_jf1','ra2sql.py',314),
  ('join_func -> LJOIN','join_func',1,'p_jf2','ra2sql.py',318),
  ('join_func -> RJOIN','join_func',1,'p_jf3','ra2sql.py',322),
  ('join_func -> FJOIN','join_func',1,'p_jf4','ra2sql.py',326),
  ('binario -> NJOIN','binario',1,'p_bin1','ra2sql.py',330),
  ('binario -> UNION','binario',1,'p_bin2','ra2sql.py',334),
  ('binario -> INTERSECT','binario',1,'p_bin3','ra2sql.py',338),
  ('binario -> EXCEPT','binario',1,'p_bin4','ra2sql.py',342),
]
